### ISSUE TITLE
Ubuntu版本无法登录

### ISSUE THREAD

**Issue by tqf6** [Websoft9/ansible-superset#11]
**Describe the bug**

## Deployment method

- [x] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [x] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [x] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

![image](https://user-images.githubusercontent.com/83911329/120257108-2d09e800-c2c2-11eb-85ad-acef4c7f2e6e.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by zengxc-1996** [comment]
tested random  password  on aliyun  ubuntu 20.04 OK  👍 
```
ok: [47.242.199.87] => {
    "end_check_versions.stdout_lines": [
        "Docker version 20.10.6, build 370c289",
        "nginx version: nginx/1.20.1",
        "Docker version 20.10.6, build 370c289",
        "pgadmin version: \"Version 5.3\" accesskey",
        "superset_version:  \"0.999.0dev\",",
        "postgres_version: 10.17",
        "redis_version: 6.2.4",
        "System version: Ubuntu 20.04",
        "Image name: supersetzengxc-Ubuntu20.04"
    ]
}

```

**Comment by jiaosir-cn** [comment]
aliyun ubuntu 20.04 test ok
```
Docker version 20.10.7, build f0df350
nginx version: nginx/1.20.1
Docker version 20.10.7, build f0df350
pgadmin version: "Version 5.3" accesskey
superset_version:  "0.999.0dev",
postgres_version: 10.17
redis_version: 6.2.4
System version: Ubuntu 20.04
Image name: supersetjiaosir-Ubuntu20.04
```

**Comment by jiaosir-cn** [comment]
aliyun ubuntu 18.04  test ok
```
Docker version 20.10.7, build f0df350
nginx version: nginx/1.20.1
Docker version 20.10.7, build f0df350
pgadmin version: "Version 5.3" accesskey
superset_version:  "0.999.0dev",
postgres_version: 10.17
redis_version: 6.2.4
System version: Ubuntu 18.04
Image name: supersetjiaosir-Ubuntu18.04
```
