### ISSUE TITLE
Invalid login

### ISSUE THREAD

**Issue by jiaosir-cn** [Websoft9/ansible-superset#12]
**Describe the bug**

基于镜像开机   登录,输入账号密码  提示 无效登录 Invalid login    三次镜像开机 出现了两次  大概率出现

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [x] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [x] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [x] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [x] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
Docker version 20.10.7, build f0df350
nginx version: nginx/1.20.1
Docker version 20.10.7, build f0df350
pgadmin version: "Version 5.3" accesskey
superset_version:  "0.999.0dev",
postgres_version: 10.17
redis_version: 6.2.4
System version: Ubuntu 20.04
Image name: superset0.999-UbuntuLTS20.04
```

### Bug Screenshot
![image](https://user-images.githubusercontent.com/76861519/122279870-206ccd00-cf1b-11eb-8833-d13309670e1a.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
重新生产制作镜像，镜像制作有误

**Comment by qiaofeng1227** [comment]
容器删除后，等待时间从20s-40s，ok
![image](https://user-images.githubusercontent.com/43192516/123241417-b99b7500-d513-11eb-9c9f-d9673591b194.png)

**Comment by qiaofeng1227** [comment]
reason: when delete volumes, docker may be running status

**Comment by qiaofeng1227** [comment]
try to restart container
