### ISSUE TITLE
Superset on aliyun-centos and Superset on aliyun-ubuntu failed to log 

### ISSUE THREAD

**Issue by chenyujie0116** [Websoft9/ansible-superset#20]
**Describe the bug**

Superset on aliyun-centos and Superset on aliyun-ubuntu log failed.
But Superset on qcloud-centos and Superset on qcloud-ubuntu log succeeded.

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [x] Ubuntu20.x
- [x] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [x] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
We can pip install module at hosted vm, but can't install module at container.
```
[root@iZbp1bp9xjr41lb4a6wsdaZ ~]# pip uninstall elasticsearch-dbapi
Found existing installation: elasticsearch-dbapi 0.2.5
Uninstalling elasticsearch-dbapi-0.2.5:
  Would remove:
    /usr/local/lib/python3.6/site-packages/elasticsearch_dbapi-0.2.5.dist-info/*
    /usr/local/lib/python3.6/site-packages/es/*
Proceed (Y/n)? y
  Successfully uninstalled elasticsearch-dbapi-0.2.5

```
