### ISSUE TITLE
Update to 1.0

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-superset#6]
Update to 1.0

**Comment by qiaofeng1227** [comment]
superset1.0.0 unzip source is superset-1.0.0，

Error occur by running this command
```
if [ $( ls | grep "incubator-superset") ]; then mv incubator-superset* superset; fi
```

**Comment by zengxc-1996** [comment]
test superset 1.0.0 on centos 7.9:
superset random password  fail
use admin admin login:  it normal works;

postgresql  random password success;

**Comment by zxc916684603** [comment]
![Uploading image.png…]()

**Comment by zengxc-1996** [comment]
needd update password method 
![image](https://user-images.githubusercontent.com/63622990/107022570-882e4100-67e0-11eb-9e34-e0f772f3fca8.png)
![image](https://user-images.githubusercontent.com/63622990/107022240-1a821500-67e0-11eb-8e51-f8370f45982c.png)

**Comment by jiaosir-cn** [comment]
Platform: AWS
Environment: Ubuntu20.04
ip: 54.237.109.90
Installation error:
![QQ截图20210208095410](https://user-images.githubusercontent.com/76861519/107167364-b041be00-69f3-11eb-804d-0ee808588001.png)

**Comment by jiaosir-cn** [comment]
Platform: Alibaba Cloud
Environment: CentOS7.9
ip: 8.210.217.180
The installation went well, the visual interface was wrong
![superset](https://user-images.githubusercontent.com/76861519/107167886-03684080-69f5-11eb-863a-47a6d17bf6e5.png)

**Comment by jiaosir-cn** [comment]
Platform: AWS
Environment: Ubuntu20.04
ip: 54.237.109.90
The installation went smoothly and the database went smoothly. After logging in to the visual interface, the icon is not displayed, the page is abnormal, and it returns to normal after waiting 30 minutes

**Comment by chendelin1982** [comment]
done
